### ISSUE TITLE
Random wing music is activated when taking elevator down

### ISSUE THREAD

**Issue by chazzybuch** [paulkim26/collab-museum#135]
This may be superfluous and unnecessary to fix once Franch implements his music logic, but would be good to sort out ahead of time to avoid any future issues. Believe it has to do with the door triggers on each wing.

**Comment by FranchNotFrench** [comment]
I suspect this is related to the Section render locks being tied to music, but since the section music should only trigger once and the sections can be visited repeatedly, that logic won't work. If nothing else we can drive the section music with a single-use lock. However I am still not sure what existing logic indicates you have started a section and which indicate you have solved the meta puzzle (could use the key/medallion trigger?) and which indicate you have done this and returned to the lobby, which may not exist yet.
