### ISSUE TITLE
Adjust transparency offsets for Lobby floor planes

### ISSUE THREAD

**Issue by chazzybuch** [paulkim26/collab-museum#43]
![20230606191033_1](https://github.com/paulkim26/collab-museum/assets/135690926/a8d1d6c7-f622-4e24-8d86-db8df4908f00)
Causing some minor issues with pickable "ghosts" (don't know proper term). I think black to 0, red to -1, and the beige marble to -2 should do it.

**Comment by FranchNotFrench** [comment]
I've been having a hard time sorting this out. Seems like it should be easy
since you can only ever view these from above and in the same order. Maybe
I need to use negative numbers or something. One issue is the logic items
are all at level 0 and get hidden if you use positive numbers. Granted that
is just an editor issue. Open to suggestions.
