### ISSUE TITLE
Add exit sequence

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#56]

**Comment by FranchNotFrench** [comment]
Partially complete. You can exit the gift shop, and when you click on the Balloon (and all players are in the trigger, which is currently a Red test ball proxy) the players will teleport inside the balloon after a fade out and the music will change to the finale.

Still need to parent everything in the room except the balloon (and possibly excluding things that aren't visible during the final balloon ride) and then set the balloon flight path.

Also need to move the balloon down to sit on the 0 plane since it won't be parented to anything, and give it an initial flight path (no players inside) so the players can watch it arrive.
